[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]

[start]
cmd = "npm run start:with-roles"
