[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "node railway-seed.js && node dist/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
