[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "chmod +x migrate.sh && ./migrate.sh && ./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
