[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "npm run start:with-roles"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
