[build]
builder = "NIXPACKS"
buildCommand = "npm install && chmod +x inject-env.sh && ./inject-env.sh"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
